apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: projnamespace
  labels:
    chapter: confmap
type: kubernetes.io/basic-auth
data:
  API_KEY: bWVnYV9zZWNyZXRfa2V5
  password: cmVhbGx5X3NlY3JldF92YWx1ZTE=
